### ISSUE TITLE
Question: How to get an error value?

### ISSUE THREAD

**Issue by marcino239** [ntwilson/result-dotnet#30]
Very cool library!

Is there a way to get error value when I know it is an error (i.e. result.IsError == true )?

Best Regards,
Marcino239

**Comment by ntwilson** [comment]
Thanks!
The simplest answer is to cast it as an Error first, and then use the `.Item` property.  I'm assuming you're using C#, and your Result is perhaps of type `Result<int, string>` then it would look like `((Result<int,string>.Error)result).Item`
That said, it's not the most idiomatic way to extract an error.  If it's possible, oftentimes it's cleaner to use `.Match` and avoid the `IsError` and `IsOk` properties.  E.g., changing
```
if (result.IsOk) {
  var i = result.Expect();
  ...
}
else {
  var err = ((Result<int,string>.Error)result).Item;
  ...
}
```
with something like
```
result.Match(
  ok: i => {
     ...
  },
  error: err => {
    ...
  }
);
```
Though that's not always possible.

Note you could also use `.Match` to extract the Error:
```
result.Match(
  err: err => err,
  ok: _ => { throw new InvalidOperationException(...); }
);
```

**Comment by marcino239** [comment]
Perhaps it would make sense to add a method like this:
```
GetError() => result.Match( err: err => err, ok: _ => { throw new InvalidOperationException(...); });
```
I've implmented above as an extension method, but it would be nice if it was already present in the library.

Best Regards,
Marcino239

**Comment by ntwilson** [comment]
Yeah I agree that could be helpful as a parallel to `Expect`.  I would consider naming it something like `ExpectError` to clearly communicate that it throws an Exception for situations where there is no `Ok` value.  I'll be honest though that most of the work for this particular library/nuget package has been discontinued after being incorporated into [SafetyFirst](https://github.com/ntwilson/SafetyFirst) ([nuget](https://www.nuget.org/packages/SafetyFirst/4.0.1)), so that's probably not something that I would take the time to implement in here.

**Comment by marcino239** [comment]
Ok - cool.  Thanks for the hint.
